---

- name: Playbook templates
  hosts: localhost
  vars:
   favourite_colour: blue
   voting_center: m2i_mougins
   fruits:
    - orange
    - pomme
    - banane

  vars_prompt:
   - name: "age"
     prompt: "How old are you?"
     private: no

  tasks:
   - name: template test
     template:
       src: ../templates/test.conf.j2
       dest: /tmp/test.conf
