---
- name: Edit html file of workers based on when condition
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: put content cible1
      copy:
        content: "ici c'est serveur dev"
        dest: /var/www/html/index.html
      when: ansible_hostname == "cible1"
 
    - name: put content cible2
      copy:
        content: "ici c'est serveur prod"
        dest: /var/www/html/index.html
      when: ansible_hostname == "cible2"

    - name: firewalld démarré
      service:
        name: httpd
        state: started

    - name: do permit traffic in default zone on port 80/tcp
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes
